### ISSUE TITLE
php-fpm executes in /var/www

### ISSUE THREAD

**Issue by pierreozoux** [lalop/invoice-ninja-docker#2]
When you set up workdir, it is for every subsequent command.
Is it desired in this case for php-fpm?

**Comment by lalop** [comment]
Maybe I'm wrong but if I want to run an `artisan` command the fact that I don't have to define the working directory into the `docker run` command can be confortable.
Is'nt the case ?

**Comment by lalop** [comment]
ok, auto-correct if what I said is right I should set the workdir to `/var/www/app`, I setted it to `/var/www` because it's the place where I want to dl the application

**Comment by pierreozoux** [comment]
Ok, if it is working, then it is fine :)
