### ISSUE TITLE
makes a better compose

### ISSUE THREAD

**Issue by pierreozoux** [lalop/invoice-ninja-docker#3]
https://github.com/lalop/invoice-ninja-docker/blob/master/docker-compose.yml#L19 is not necessary (as already defined in Dockerfile)

You could put this in the Dockerfile: https://github.com/lalop/invoice-ninja-docker/blob/master/docker-compose.yml#L18

Can't you use the linked env var? (to DRY a bit :) )
https://github.com/lalop/invoice-ninja-docker/blob/master/docker-compose.yml#L16-L17

https://github.com/lalop/invoice-ninja-docker/blob/master/docker-compose.yml#L5-L6
I actually use root user, it saves some lines :) But I think it is a matter of taste :)
(I don't see much the point of the overhead of creating a user in a unique database but maybe I'm wrong?)

**Comment by lalop** [comment]
I splited this issue in 3 :
- https://github.com/lalop/invoice-ninja-docker/issues/4
- https://github.com/lalop/invoice-ninja-docker/issues/5
- https://github.com/lalop/invoice-ninja-docker/issues/6
- https://github.com/lalop/invoice-ninja-docker/issues/7
